name: CI Pipeline

on:
  pull_request:
    branches: ["develop"]
  push:
    branches: ["develop"]

jobs:
  backend:
    name: Build & Test Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17

      - name: Build backend with Maven
        working-directory: backend/dockerhub-clone
        run: mvn -B clean verify

  frontend:
    name: Build & Test Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Run lint/test
        working-directory: frontend
        run: npm run build
